server:
  port: 8080

security:
  basic:
    enable: false

spring:
  application:
    name: readingIsGood
  datasource:
    url: jdbc:mysql://localhost:3307/getir
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      minimumIdle: 10
      maximumPoolSize: 30
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update